### ISSUE TITLE
No se usa base de datos

### ISSUE THREAD

**Issue by isaioliva** [remozwell/Taxi24#1]
Hola 

la aplicación no esta usando base de datos, ya apague todos los servicios de base de datos que tengo y aún así me sigue contestando, al parecer esta usando un archivo o código duro, por favor revisa. La aplicación no me creó ninguna tabla en la base de datos.

**Comment by remozwell** [comment]
Buenas, en el readme especifique que para usar la base de datos debe
configurar el appsetings colocando el connection string de su servidor de
base de datos y poniendo el key "UseSQLite" en false en el mismo
appsetting.json

**Comment by isaioliva** [comment]
me sale este error

'Taxi24RestAPI.dll' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_64\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Taxi24RestAPI.dll' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\testEVO\jose_enrique\Taxi24RestAPI\bin\Debug\netcoreapp3.1\Taxi24RestAPI.dll'. Symbols loaded.
An unhandled exception of type 'System.IO.FileNotFoundException' occurred in Unknown Module.
Could not load file or assembly 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

The program '[35428] Taxi24RestAPI.dll' has exited with code -1 (0xffffffff).


appsettings
{
  "ConnectionStrings": {
    "TaxiDBConnection": "Data Source=localhost; Initial Catalog=Taxi24; Persist Security Info=True; Connection Timeout=6000; User Id =sa; Password =*******;"
    //"TaxiDBConnection": "Server=localhost\\SQLEXPRESS01;Database=DB_Taxi24;Trusted_Connection=True;",
    //"TaxiDBConnection": "Server=localhost;Database=DB_Taxi24;Trusted_Connection=True;"
  },
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
  "AllowedHosts": "*",
  "UseSQLite": false,
  "SQLiteFile": "TaxiDB.db",
  "KMDefaultRadius": 3,
  "ConductoresDisponiblesDefault": 3,
  "CostoBase": 17.5,
  "CostoKilometro": 23.4,
  "CostoMinuto": 4.8

}

**Comment by remozwell** [comment]
Buenas noches,

Revisé el proyecto y a mi me arranca bien, estuve investigando mas a fondo
el error y al parecer se debe a algunos módulos que no se cargan por la
configuración del proyecto. Hice los cambios que me recomendaron para
solucionar el problema. En caso de que no le funcione aun le exhorto a que
deshabilite la opción "Just My Code" (ubicado en tools - options -
debugging - general - enabled just my code) puesto que también es una de
las razones del problema (Module is optimized and the debugger option '*Just
My Code'* is enabled.).

Saludos

**Comment by isaioliva** [comment]
@remozwell estimado de parte de RRHH te estan buscando,

**Comment by isaioliva** [comment]
podrías compartirnos un número para localizarte vía mail por favor.
